version: '3'
services:
  node_alice:
    container_name: alice
    image: socialnetwork/chi:${TAG:-latest}
    ports:
      - "30333:30333"
      - "9933:9933"
      - "9944:9944"
    volumes:
      - "chi-data-alice:/data"
    command: --validator --alice --port 30333 --rpc-port 9934 --ws-port 9944
    networks:
      testing_net:
        ipv4_address: 172.28.1.1

  node_bob:
    container_name: bob
    image: socialnetwork/chi:${TAG:-latest}
    ports:
      - "8000:9934"
      - "9000:9944"
    volumes:
      - "chi-data-bob:/data"
    command: --validator --bob --port 3033 --rpc-port 9934 --ws-port 9944
    networks:
      testing_net:
        ipv4_address: 172.28.1.2

  node_charlie:
    container_name: charlie
    image: socialnetwork/chi:${TAG:-latest}
    ports:
      - "8100:9933"
      - "9100:9944"
    volumes:
      - "chi-data-charlie:/data"
    command: --validator --charlie --rpc-port 9933 --ws-port 9944
    networks:
      testing_net:
        ipv4_address: 172.28.1.3

  node_dave:
    container_name: dave
    image: socialnetwork/chi:${TAG:-latest}
    ports:
      - "8200:9933"
      - "80:9944"
    volumes:
      - "chi-data-dave:/data"
    command: --dave --rpc-port 9933 --ws-port 9944 --ws-external --rpc-cors all
    networks:
      testing_net:
        ipv4_address: 172.28.1.4

volumes:
  chi-data-alice:
  chi-data-bob:
  chi-data-charlie:
  chi-data-dave:

networks:
  testing_net:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16
